server:
    port: 8092

spring:
    application:
        name: microservice-user-consumer-hystrix

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/


provider:
    url: http://MICROSERVICE-USER-PROVIDER/api/user/

