server:
    port: 8761

spring:
    application:
        name: microservice-eureka-server
    security:
        user:
            name: admin
            password: admin

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        serviceUrl:
            defaultZone: http://localhost:${server.port}/eureka/